### ISSUE TITLE
Borrow rules from eslint-plugin-relay

### ISSUE THREAD

**Issue by ashfurrow** [relay-tools/tslint-plugin-relay#7]
I'm going to look at [eslint-plugin-relay's rules](https://github.com/relayjs/eslint-plugin-relay/tree/master/src) and see what makes sense to port over. I'll list them here and work away on them. 

Edit: here's a list of their rules:

- [x] rule-compat-uses-vars.js (#16)
- [x] rule-generated-flow-types.js (#15)
- [x] rule-graphql-naming.js (#14)
- [x] rule-graphql-syntax.js (#12)
- [x] rule-no-future-added-value.js (#13)

I'll check them off as I browse rules.

**Comment by ashfurrow** [comment]
Okay, I've got these defined in their own issues, so I'm going to close this one and move them into a Milestone.
